name: frontend
description: "SafeTravel India - Smart Tourist Safety System"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.0
  
  # State Management
  flutter_riverpod: ^2.6.1
  
  # Navigation
  go_router: ^15.1.2
  
  # Animations
  flutter_animate: ^4.3.0
  
  # Maps
  flutter_map: ^6.1.0
  flutter_map_cancellable_tile_provider: ^2.0.0
  latlong2: ^0.9.0
  geolocator: ^13.0.2
  http: ^1.2.0
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  
  # Utilities
  equatable: ^2.0.5
  url_launcher: ^6.3.1
  device_info_plus: ^11.1.0
  
  # AI Chatbot
  google_generative_ai: ^0.4.3
  flutter_dotenv: ^5.1.0

  permission_handler: ^12.0.1
  font_awesome_flutter: ^10.12.0
  model_viewer_plus: ^1.10.0
  universal_html: ^2.3.0
  firebase_analytics: ^11.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/env
  
  shaders:
    - shaders/nebula.frag
